# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Just Me
# Description of the Site
description: Blog enfocado en temas de IT
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Blog
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://cdn.hipwallpaper.com/m/83/71/cnbFNM.jpg
# https://hdwallsource.com/img/2015/9/geek-wallpaper-47746-49302-hd-wallpapers.jpg
# V1 https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: lomv0209@gmail.com
#facebook_username: /
twitter_username: zzjust_mezz
instagram_username: / 
linkedin_username: luis-octavio-mota-verdasco-sys-admin
github_username: Lucho00Cuba
youtube_channel_id: UCledsaFq1uBeyGbmxzSG_4Q
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
#google-analytics: 

# Disqus
#disqus-shortname:

# Name of the Author
author-name: Lucho
# URL for the Image of the Author
author-image: https://avatars.githubusercontent.com/u/55890128?v=4
# 60 Words About the Author
author-about: Joven aficionado al mundo de la Informática y las Tecnologías. Gran pasión sobre el montaje, instalación, administración de sistemas y redes informáticas. Interesado en una carrera desafiante en la que expandir y aplicar conocimientos informáticos
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Lucho00Cuba

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
